### ISSUE TITLE
Unable to run kubebox on MacOS Big Sur

### ISSUE THREAD

**Issue by emmekappa** [astefanutti/kubebox#105]
I'm getting the following error on MacOS Big Sur running kubebox v0.8.0

```
./kubebox
[1]    9256 killed     ./kubebox
```

**Comment by astefanutti** [comment]
It may be the quarantine flag has to be removed from the binary, e.g.:

    $ xattr -d com.apple.quarantine kubebox

**Comment by emmekappa** [comment]
@astefanutti it was my first tought too but... 
`xattr: kubebox: No such xattr: com.apple.quarantine`

**Comment by astefanutti** [comment]
It may be Big Sur sets new constraints on downloaded binaries. I need to research it and eventually test it as soon as I have access to a MacOS Big Sur computer.

**Comment by astefanutti** [comment]
It may be related to https://github.com/upx/upx/issues/424.

I've prepared a Mac OS binary for the upcoming release and haven't compressed it with UPX. Could you please try and let me know if that works:

[kubebox.gz](https://github.com/astefanutti/kubebox/files/5552037/kubebox.gz)

**Comment by emmekappa** [comment]
@astefanutti yes! it runs smoothly

**Comment by astefanutti** [comment]
@emmekappa great! Thanks a lot for the feedback. I'll probably publish the MacOS binary un-compressed for the next release, as it's too much trouble to use UPX for MacOS.

**Comment by astefanutti** [comment]
I've published the binary in 0.9.0 release. Thanks a lot!
