### ISSUE TITLE
terminal does not support input Chinese words ???

### ISSUE THREAD

**Issue by zhixiaoqiang** [astefanutti/kubebox#111]
input: 哈哈哈哈
display: (empty)

input: 阿斯达
display: ?

![image](https://user-images.githubusercontent.com/25545093/99634699-e1a59000-2a7b-11eb-9279-988104a3ec26.png)

**Comment by astefanutti** [comment]
Thanks a lot for the report. This should be fixed with c4f6778e9fecb1a52e95bc9a687b6f303e077c32.

**Comment by zhixiaoqiang** [comment]
> Thanks a lot for the report. This should be fixed with [c4f6778](https://github.com/astefanutti/kubebox/commit/c4f6778e9fecb1a52e95bc9a687b6f303e077c32).

Surprise，thanks!!!
