### ISSUE TITLE
Unable to locate cAdvisor pod on node

### ISSUE THREAD

**Issue by justinrush** [astefanutti/kubebox#116]
I can't see any resource metrics when running kubebox against a VMware Tanzu cluster. I see this error:

```
Unable to locate cAdvisor pod on node my-node-guid
```

My environment:
* kubectl version: 1.18.6
* k8s version: v1.18.6+vmware.1
* kubebox: 0.9.0

in case it matters, I use kubectl-krew w/ kubectl-ns plugin.

**Comment by astefanutti** [comment]
Did you follow the installation instructions documented in https://github.com/astefanutti/kubebox#cadvisor?

Also the FAQ section may help: https://github.com/astefanutti/kubebox#faq.

**Comment by justinrush** [comment]
following the instructions??? wow, amazing, that made it work :)

Thanks for pointing that out, sorry for not reading all the way through.
