### ISSUE TITLE
I can't get it to run on my desktop computer. Throws "TyperError: require(...).runMain is not a function"

### ISSUE THREAD

**Issue by abrown28** [astefanutti/kubebox#125]
I installed it via scoop on my desktop and I get the following error. It works fine on my laptop with the same windows version and node version.
```
Scoop was updated successfully!
Installing 'kubebox' (0.9.0) [64bit]
kubebox-windows.exe (14.0 MB) [=======================================================================================================================================================================================================] 100%
Checking hash of kubebox-windows.exe ... ok.
Linking ~\scoop\apps\kubebox\current => ~\scoop\apps\kubebox\0.9.0
Creating shim for 'kubebox'.
Creating shortcut for Kubebox (kubebox.exe)
'kubebox' (0.9.0) was installed successfully!
PS C:\Users\abrown28> kubebox
C:\Users\abrown28\scoop\apps\kubebox\current\kubebox.exe:352
    })();;;require("module").runMain();
                             ^

TypeError: require(...).runMain is not a function
    at Object.<anonymous> (C:\Users\abrown28\scoop\apps\kubebox\current\kubebox.exe:352:30)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at internal/bootstrap/pre_execution.js:115:36
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:116:3)
    at internal/main/run_main_module.js:7:1
PS C:\Users\abrown28> node --version
v14.16.1
```

I've tried it in `cmd` and powershell 7-preview today.
It had the same error in the older powershell when I tried it a couple of months ago.

There is obviously a difference between my desktop and my laptop but I can't think of what to check.

It works in WSL if I download it from git

**Comment by astefanutti** [comment]
Could you please give it a try with the newest version release: https://github.com/astefanutti/kubebox/releases/download/v0.10.0/kubebox-windows.exe

**Comment by abrown28** [comment]
That ran.
unfortunately I don't have a k8s cluster to point it at but it did come up and complain :)

Thank you

**Comment by astefanutti** [comment]
Thanks for the prompt feedback. I think that's enough to confirm it's fixed, as it would not even start otherwise. Feel free to re-open if needed.
