### ISSUE TITLE
Can't run version 0.10.0 on Windows 11

### ISSUE THREAD

**Issue by tech189** [astefanutti/kubebox#139]
I tried downloading the latest version from the releases page but when I double click to open it I get the following message:

![image](https://user-images.githubusercontent.com/10728085/162639758-7dabfe57-1c38-4b42-9423-a6398ae17d3e.png)

Also, the previous version doesn't run either (just as issue #125):
```
D:\Downloads\kubebox-windows.exe:352
    })();;;require("module").runMain();
                             ^

TypeError: require(...).runMain is not a function
    at Object.<anonymous> (D:\Downloads\kubebox-windows.exe:352:30)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at internal/bootstrap/pre_execution.js:115:36
    at prepareMainThreadExecution (internal/bootstrap/pre_execution.js:116:3)
    at internal/main/run_main_module.js:7:1

[process exited with code 1 (0x00000001)]
```

**Comment by astefanutti** [comment]
Thanks for the report.

Could you please retry with a newer version, that's without UPX compression, and that I've just re-uploaded here:

https://github.com/astefanutti/kubebox/releases/download/v0.10.0/kubebox-windows.exe

**Comment by tech189** [comment]
That works! :)

**Comment by astefanutti** [comment]
Great! Thanks a lot for the feedback!
