### ISSUE TITLE
cAdvisor daemonset not working anymore with k8s >= 1.25

### ISSUE THREAD

**Issue by ecky-l** [astefanutti/kubebox#148]
As the `PodSecurityPolicy` has been removed, the cAdvisor daemonset (cadvisor.yaml) does not work anymore. It needs to be migrated according to the information and guides on this page:

https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Comment by astefanutti** [comment]
Thanks for the report. I've removed the PSP in fc2f57440ad9eee4c92b319397689e009867fec0 which should fix the issue. It's possible that further configuration is required depending on the Kubernetes distro. Let me know if you face any issue.
