### ISSUE TITLE
Quick jump a namespaces ?

### ISSUE THREAD

**Issue by Sn0rt** [astefanutti/kubebox#15]
can I jump a namespaces quickly?

**Comment by johnpoth** [comment]
Can you change namespaces by pressing the `n` key

**Comment by Sn0rt** [comment]
I hava a hundred namesapces in fact.

**Comment by astefanutti** [comment]
I was thinking of having a quick search filter in the namespaces modal. Would that work for you?

**Comment by Sn0rt** [comment]
@astefanutti agree with , aha, I has a special scene which is pre tenant pre namespaces.

**Comment by astefanutti** [comment]
> It also might be worth adding one for the pods as well

@johnpoth good point! I was thinking we could have a search filter for logs and even the remote exec terminal. So Pretty much for all panels.
