### ISSUE TITLE
Docker build not working

### ISSUE THREAD

**Issue by fpaparoni** [astefanutti/kubebox#153]
I'm trying to make some changes to the sourcecode but if I build the Docker image using the following standard command

    docker build -t kubebox-custom . 

I receive this error

     "/kubebox/bundle.js": not found

in response to this command from the Dockefile

     [stage-1 5/7] COPY --from=builder /kubebox/bundle.js /kubebox/client.js:

I tried to enter in the builder container and I can see there isn't a bundle.js file

![image](https://github.com/astefanutti/kubebox/assets/4602065/bd27b365-1f12-4d3a-a421-4cd5ea348478)

Is there something I'm doing wrong or isn't the builder container working properly?

**Comment by fpaparoni** [comment]
The [problem seems related](https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported) to some changes in Node 17 related to obsolete version of SSL. 

I tried to locally set nvm to use node 16 and "npm run bundle" works but anyway it doesn't produce bundle.js and client.js in the root folder. I find only bundle.js under dist/js/bundle.js with the webpack configuration so I suppose there is something wrong with the Dockerfile

**Comment by astefanutti** [comment]
Thanks for the analysis. The Dockerfile relies on Node 12 which is indeed rather old. If you have an updated Dockerfile that works with a more recent version of Node, feel free to create a PR, I'd be happy to merge it!

**Comment by fpaparoni** [comment]
No sorry I'm trying to understand, but it seems like the actual Dockerfile (apart from this problem related to Node 17) has some problems related to paths.

I see problems this row in the Dockerfile

    COPY --from=builder /kubebox/bundle.js /kubebox/client.js

because bundle.js is generated in a different path from webpack and client.js is inside another directory (lib). Is it an old version of Dockerfile of this project?

**Comment by astefanutti** [comment]
Ah got you. That's the Dockerfile for the project, so it's supposed to work. If it doesn't that's possible it's been broken, probably with some Webpack update.

**Comment by fpaparoni** [comment]
I see inside **lib** folder most relevant part of js files. Is it the path from which I can start the **client.js** using node?

**Comment by fpaparoni** [comment]
I changed this row

    COPY --from=builder /kubebox/dist/js/bundle.js /kubebox/client.js

and the build works, but if I try to run it I have the execution of the node command directly in my console. I need to start it as I have done with the image published on dockerhub, to use it with the browser. 

I saw there are two Dockerfile, one at root level and another inside docs. Which is the one used for the image kubebox which I installed in a remote cluster and (I know it should be simply docker run -t IMAGENAME) which is the command to run it?

**Comment by fpaparoni** [comment]
ok great, it is like I supposed. But if I change something on the "main" folder, is there the need to copy something on the docs folder? Because I saw in docs folder there is only a kubebox.js without a relationship with the "main" folder. Is there some script/target to run to update also docs folder from the main folder?

**Comment by astefanutti** [comment]
Right, you need to run `npm run browserify` to update the content of the `docs` directory.
