### ISSUE TITLE
The "kubik" name on npmjs.com

### ISSUE THREAD

**Issue by aslushnikov** [astefanutti/kubebox#155]
Hi folks,

I'm Andrey, creator of Puppeteer and a former core team member of Playwright. These days, I’m working on flakiness.io, and as part of the project, we’ve built a small, in-house system called “kubik” to manage our builds.

As we’re considering open-sourcing it, we noticed that the name “kubik” is already in use on npmjs.com, though it hasn’t had any activity in over seven years. Would you be open to donating this name to us? If not, no worries at all – we’ll find another name.

Thanks very much for considering it!

Best,
Andrey

**Comment by astefanutti** [comment]
Hi Andrey, sure I'd be happy to transfer it to you. Please send me you NPM username and I'll transfer ownership to you.

It'll be my small appreciation for the awesome work you've done on Puppeteer that I've used for many years now in https://github.com/astefanutti/decktape 🙇🏼.

**Comment by aslushnikov** [comment]
Thanks a lot, we really appreciate this! My npm account is https://www.npmjs.com/~aslushnikov

**Comment by astefanutti** [comment]
@aslushnikov I've just invited you. I'll remove myself once you accept the invite.

**Comment by aslushnikov** [comment]
Yep, accepted the invitation.

Thank you again @astefanutti!

**Comment by astefanutti** [comment]
I've just removed myself. It's all yours!
