### ISSUE TITLE
Select pod log

### ISSUE THREAD

**Issue by lcd1232** [astefanutti/kubebox#17]
Add ability to select logs for copy selected text.

**Comment by astefanutti** [comment]
Would definitely be helpful! I can't reminder the countless time I tried copying from the log 😄.

Similar to #10 for clipboard integration.

**Comment by johnpoth** [comment]
As a poor consolation, you can always bypass the signal processing by pressing down "shift" and then select -> copy

**Comment by 593769290** [comment]
Is that possiable to just using blessed-xterm to show log ? blessed-xterm support clipboardy so well.

**Comment by astefanutti** [comment]
@593769290 

> Is that possiable to just using blessed-xterm to show log ? blessed-xterm support clipboardy so well.

Yes, I had the same idea. I think it'd be possible to use the Xterm buffer instead of the Blessed one for the log widget, and reuse the clipboard integration we've developed for the remote terminal.

**Comment by 593769290** [comment]
so, we will hear some good  news next week?

**Comment by astefanutti** [comment]
> so, we will hear some good news next week?

I wish but that sounds very optimistic, unless you feel like helping 😉. I'll definitely look into it ASAP, as I share your pain!

**Comment by 593769290** [comment]
Dose something moves on about this issue? 

waiting for select and copy log txt.

**Comment by astefanutti** [comment]
@593769290 It has yet to be worked on. We'll keep you posted.

**Comment by astefanutti** [comment]
I've just created #110 that switches the logs widget to using the Xterm.js buffer. This works very well. I'll factorize the clipboard integration so that this will be fixed soon.

**Comment by astefanutti** [comment]
It is fixed with c85478e270f67236f19971021f99d02769ad636b.
