### ISSUE TITLE
Connection failed to https

### ISSUE THREAD

**Issue by 18611240676** [astefanutti/kubebox#23]
![image](https://user-images.githubusercontent.com/42232231/47688967-b6e10880-dc22-11e8-8ef0-fe8cafb84e91.png)
What's wrong with that? thanks!

**Comment by astefanutti** [comment]
As it seems you're using the hosted Web version, it requires proper CORS configuration on the API server. You can find some information at https://github.com/astefanutti/kubebox#online.

To confirm it is a CORS issue, you can open the console panel in your Web browser and check the error messages.

**Comment by astefanutti** [comment]
Let me close this. Feel free to re-open if it turns out it's not a CORS issue.
