### ISSUE TITLE
Problem with scrolling logs on Windows 10

### ISSUE THREAD

**Issue by szegi** [astefanutti/kubebox#31]
I don't know if it's intended but i can't scroll logs from selected pod
I see when there is new info added
but i can't scroll it up or down using these shortcuts
![obraz](https://user-images.githubusercontent.com/12111506/50833904-f62e8280-1352-11e9-8db0-47de0213382e.png)

Im using release 0.3.2 on Windows 10, and i have info in Resources that "Resource usage metrics is unavailable"

**Comment by astefanutti** [comment]
> I don't know if it's intended but i can't scroll logs from selected pod
I see when there is new info added
but i can't scroll it up or down using these shortcuts

I think you need to click on the log widget so that it has focus and receives the shortcut events.

> Im using release 0.3.2 on Windows 10, and i have info in Resources that "Resource usage metrics is unavailable"

It is either due to permissions or your cluster version, see #11.

**Comment by szegi** [comment]
I run it using kubebox.exe and i don't see how to focus on log widget, it looks like normal cmd app
![obraz](https://user-images.githubusercontent.com/12111506/50885343-bec0e400-13ed-11e9-8e93-ddd5aa124f3c.png)

**Comment by astefanutti** [comment]
You can five focus on the logs widget by clicking on it. Then you should be able to use the shortcuts.

You should be able to scroll the logs with the mouse wheel as well. It works on Linux and Mac OS but I haven't tested it on Windows 10.

**Comment by szegi** [comment]
On windows i can't focus on anything:/
i can use shortcuts, but if they depend on focus
i am not able to use it
maybe option for global shortcuts like these M,C,T
i don't need focus there

**Comment by astefanutti** [comment]
I get your point. I wonder if mouse support actually works on Windows 10. It may depend on your terminal emulator configuration. By chance, does clicking on the _debug_ tab work?

**Comment by johnpoth** [comment]
I wonder if running it in Cygwin makes a difference...

**Comment by szegi** [comment]
> By chance, does clicking on the _debug_ tab work?

No it doesnt change anything

> I wonder if running it in Cygwin makes a difference...

I tried to run ./kubebox.exe in cygwin but it doesn't work at all or i'm doing something wrong

**Comment by szegi** [comment]
any news on this?:)

**Comment by astefanutti** [comment]
@szegi unfortunately no. Can you just check that clicking on the _debug_ tab works? That will confirm that mouse support does not work on your Windows environment.

I still need to have a proper Windows environment to troubleshoot. Otherwise, I think we need to work on a solution that could change focus from the keyboard, like TAB and SHIFT+TAB.

**Comment by szegi** [comment]
I tried and it didn't work, i will also try on my home computer later today

**Comment by code-to-joy** [comment]
I cannot get the mouse to work in the console. It works in the console in general, but not in kubebox. I also cannot scroll the log window, as the others above.

**Comment by astefanutti** [comment]
@code-to-joy can you confirm you're using Windows OS?

**Comment by code-to-joy** [comment]
@astefanutti I can. Windows 10. I also noticed that it actually works in a different shell emulator. I'm using "cmder" (which is ConEmu in the foundation) when it doesn't work. When I switch over to "Terminus", it actually works.

**Comment by astefanutti** [comment]
@code-to-joy thanks for the feedback.

It seems most terminal emulators on Windows do not support mouse events. We'll try to dig into this. Otherwise, more generally, I think a keyboard-only navigation would be a plus, and would mitigate the lack of mouse support on Windows.

**Comment by astefanutti** [comment]
Fixed with #104.

**Comment by 625781186** [comment]
> @code-to-joy感谢您的反馈。
> 
> Windows 上的大多数终端模拟器似乎都不支持鼠标事件。我们将尝试深入研究这一点。否则，更一般地说，我认为仅使用键盘的导航将是一个加分项，并且可以缓解 Windows 上缺少鼠标支持的情况。



> @code-to-joy thanks for the feedback.
> 
> It seems most terminal emulators on Windows do not support mouse events. We'll try to dig into this. Otherwise, more generally, I think a keyboard-only navigation would be a plus, and would mitigate the lack of mouse support on Windows.



> @code-to-joy thanks for the feedback.
> 
> It seems most terminal emulators on Windows do not support mouse events. We'll try to dig into this. Otherwise, more generally, I think a keyboard-only navigation would be a plus, and would mitigate the lack of mouse support on Windows.

No , 
https://github.com/migueldeicaza/gui.cs
https://github.com/prompt-toolkit/python-prompt-toolkit  ,
they ary both support mouse on win10 .

It's kubebox can't support mouse click on win10  ?

**Comment by 625781186** [comment]
> > @code-to-joy感谢您的反馈。
> > Windows 上的大多数终端模拟器似乎都不支持鼠标事件。我们将尝试深入研究这一点。否则，更一般地说，我认为仅使用键盘的导航将是一个加分项，并且可以缓解 Windows 上缺少鼠标支持的情况。
> 
> > @code-to-joy thanks for the feedback.
> > It seems most terminal emulators on Windows do not support mouse events. We'll try to dig into this. Otherwise, more generally, I think a keyboard-only navigation would be a plus, and would mitigate the lack of mouse support on Windows.
> 
> > @code-to-joy thanks for the feedback.
> > It seems most terminal emulators on Windows do not support mouse events. We'll try to dig into this. Otherwise, more generally, I think a keyboard-only navigation would be a plus, and would mitigate the lack of mouse support on Windows.
> 
> No ,
> https://github.com/migueldeicaza/gui.cs
> https://github.com/prompt-toolkit/python-prompt-toolkit ,
> they ary both support mouse on win10 .
> 
> It's kubebox can't support mouse click on win10 ?

Oh , It's a reason about https://github.com/chjj/blessed can't support mouse on win10.
