### ISSUE TITLE
Suggestion: Remove guide to change role of default service account on RBAC section

### ISSUE THREAD

**Issue by JCMais** [astefanutti/kubebox#34]
Making the default service account have cluster-admin role is a tremendous security vulnerability, it's probably a better idea to change the service account used on the deployment, and put the manifest to create the service account / cluster role / cluster role binding on the same file.

**Comment by astefanutti** [comment]
Thanks for the suggestion. Makes much sense. We'll apply it ASAP.

**Comment by JCMais** [comment]
Thanks @astefanutti, really appreciate the tool you built!

**Comment by astefanutti** [comment]
Implemented in b252eb76c9dbe4f685d87f0531788709637f6f7c. Feel free to review it.
