### ISSUE TITLE
Add support for Events

### ISSUE THREAD

**Issue by johnpoth** [astefanutti/kubebox#36]
https://kubernetes.io/docs/tasks/debug-application-cluster/
https://docs.openshift.com/container-platform/3.11/dev_guide/events.html

**Comment by astefanutti** [comment]
As a first implementation, we could just open a new tab with the content of the `describe` command, possibly restricted to the `Events` section. Another possibility is to add a tab to the log panel and provide shortcuts to navigate from log, events, or description.

This relates to #20.

**Comment by astefanutti** [comment]
Fixed with #81. It'll be part of 0.8.0 release.
