### ISSUE TITLE
Unable to view Mem/CPU/Net

### ISSUE THREAD

**Issue by cgkades** [astefanutti/kubebox#37]
I'm using 4.0 on MacOS and am unable to view resource usage. I'm met with "Resources usage metrics unavailable". There is nothing in the debug to let me know what might be going on. I am able to view resources on one of my clusters, but not any of the other ones.

**Comment by cgkades** [comment]
Is there a k8s version requirement? Seems it doesn't work on 1.11.5, but does on 1.12.6. If there is a version requirement, it might be helpful to add it to the readme

**Comment by astefanutti** [comment]
You're right, it depends on https://github.com/kubernetes/kubernetes/issues/56297 that may not have been backported in older k8s versions.

There is still #11 open to track some improvements around resource usage availability, though adding the info to the README is a good idea. That'd be great if you can create a PR, otherwise I'll do it ASAP.

**Comment by cgkades** [comment]
I can probably create a PR for you today or tomorrow

**Comment by cgkades** [comment]
Reading that linked bug leads me to believe that the error was just in 1.8.0, and that it not only worked in earlier versions, but should have worked in later ones as well. I'm not sure i'm the best person to update your readme, unless you just want a blurb in a "known issues" section where I can add that Azure Kubernetes 1.11.5 does not work but 1.12.6 does?

**Comment by astefanutti** [comment]
No worries. The issue is present from 1.8 to 1.11 as per the branches info for kubernetes/kubernetes@a82c84e0878b793a9241a4928a3de82a1b7e8adb. We could create a FAQ section and add an initial item for this monitoring issue.

**Comment by astefanutti** [comment]
I've just pushed 877e424d10831a359b3bca5edc9fe8c35a90fc12 that adds a FAQ.
