### ISSUE TITLE
What are the prerequisites for kubebox to work on a k8s cluster 

### ISSUE THREAD

**Issue by rajeshrcmc** [astefanutti/kubebox#42]
Does kubebox need metrics server running ? , will it work with kube-state-metrics

**Comment by astefanutti** [comment]
Kubebox currently retrieves resources usage metrics from the Kubelet embedded cAdvisor. So it does not need `metrics-server` nor `kube-state-metrics`. We are planning to support these in the future to add more metrics, though they will remain optional.
