### ISSUE TITLE
Prompting for login

### ISSUE THREAD

**Issue by biswasraja** [astefanutti/kubebox#46]
<img width="1859" alt="Screenshot 2019-06-19 at 12 10 43 AM" src="https://user-images.githubusercontent.com/51969338/59710578-d61abd80-9226-11e9-963b-fa6033c18aba.png">

Which credential to use?

**Comment by johnpoth** [comment]
@biswasraja those are your cluster credentials you normally use, you can check ~/.kube/config

**Comment by biswasraja** [comment]
Thanks @johnpoth , it worked.

**Comment by doronzuk** [comment]
i dont have password field in kube config... what are the exact fields from kube config to use?

**Comment by astefanutti** [comment]
@doronzuk that depends on how your cluster [authentication](https://kubernetes.io/docs/reference/access-authn-authz/authentication/) is configured. Kubebox supports almost all the _kubeconfig_ file user authentication fields. Password is generally used with static password file and OAuth strategies.
