### ISSUE TITLE
How to set RBAC for normal user

### ISSUE THREAD

**Issue by Rmond** [astefanutti/kubebox#47]
I want specific users to access specific namespaces. How should I set them up?

**Comment by astefanutti** [comment]
You should be using RBAC as authorisation mode for the API server of your cluster. This is documented in https://kubernetes.io/docs/reference/access-authn-authz/rbac/.

Then Kubebox displays the namespaces that the current logged in user has permission to access to.

**Comment by astefanutti** [comment]
Let me close this. Feel free to comment if that doesn't answer your question.
