### ISSUE TITLE
Search filter in namespace modal dialog

### ISSUE THREAD

**Issue by alexaandrov** [astefanutti/kubebox#49]
Hello!

Please add a filter to the namespace modal selection window.

Currently awfully inconvenient to choose the necessary namespace when there are more than 100...

I would be very grateful!

---

I was thinking of having a quick search filter in the namespaces modal. Would that work for you?

_Originally posted by @astefanutti in https://github.com/astefanutti/kubebox/issues/15#issuecomment-402968374_

**Comment by astefanutti** [comment]
Thanks for the report. I definitely agree it's inconvenient at the moment with 10+ namespaces.
