### ISSUE TITLE
Bug with exec auth and env

### ISSUE THREAD

**Issue by codertao** [astefanutti/kubebox#56]
PR #54 added support for exec auth, but it doesn't seem to support environment correctly.

KubeConfig from aws is of form:
  user:
    exec:
      env:
      - name: AWS_PROFILE
        value: saml

But child_process.exec is expecting env to be of form {AWS_PROFILE: saml}.

Can probably submit a PR this week if I get the time to sit down.

**Comment by astefanutti** [comment]
Thanks a lot for the report. That’d be awesome if you could create a PR. We’ll cut a new release then.

**Comment by astefanutti** [comment]
Should be fixed with 9f70c9fd8e2b6237d8a81118544779a5ce4f89e3. Thanks!
