### ISSUE TITLE
Unable to scroll terminal when running in iTerm

### ISSUE THREAD

**Issue by MelanieT** [astefanutti/kubebox#59]
When running kubebox in a container and displaying on iTerm on apple, it is not possible to scroll back in the terminal window (R-key).
iTerm doesn't pass mouse events to curses, so mouse actions scroll the local iTerm history buffer, not the terminal session. Therefore, any output longer than the height of the screen becomes inaccessible.

**Comment by astefanutti** [comment]
Thanks for the report. Could you confirm that by _running kubebox in a container_, you mean  running it with `kubectl`?

**Comment by MelanieT** [comment]
kubectl, yes. i just used your command line from the readme.

**Comment by astefanutti** [comment]
By change, would you be able to try with `docker run` in iTerm? I suspect this has more to do with how `kubectl` deal with nouse events rather than the terminal.

Here is the command to run kubebox with Docker:

    $ docker run -it --rm -v ~/.kube/:/home/node/.kube/:ro astefanutti/kubebox

**Comment by MelanieT** [comment]
Mouse events do not get forwarded. What I'm looking for is a keyboard way to scroll. I don't interact with terminals using the mouse so mouse events are diabled.

**Comment by astefanutti** [comment]
OK, then it relates to #31, for which we want to introduce full keyboard navigation and scrolling to address terminals for which mouse events are not supported or disabled.

**Comment by MelanieT** [comment]
It relates only somewhat, because the keys for log navigation are actually valid inputs in a teminal, so can't be used.
What should be used are the navigation keys, as in a Linux console - shift pgup, shift pgdn.

**Comment by astefanutti** [comment]
It should be fixed with 7da074d23626bbb94fd5120536e54db30ae7d2e4.
