### ISSUE TITLE
Show init containers logs

### ISSUE THREAD

**Issue by lduparc** [astefanutti/kubebox#61]
It will be apppreciate to be able to see initContainers logs.

~~Moreover, gettings logs on CrashloopBackOff should be interesting~~

**Comment by dolphyvn** [comment]
Interested to have those features too.

**Comment by astefanutti** [comment]
> Moreover, gettings logs on CrashloopBackOff should be interesting

It is supposed to be supported since version 0.6.0 with 2b07db88566aacf5cee7d211017ae05cc628c9f5. If it turns out it does not work for you with 0.6.0, could you please report a separate issue?

**Comment by lduparc** [comment]
Sorry CrashLoopBackOff is working with 0.6.0 version. I have updated first comment.

But InitContainers will be an interesting feature.

**Comment by astefanutti** [comment]
Thanks for the feedback. For the init containers log, it should only a matter of iterating over the `initContainers` array, as it is already done for the `containers` array. We'll add that enhancement for the next release.

**Comment by astefanutti** [comment]
This should be fixed with 2260089cc88367612d59ccb8e0ce6d3c4a8be3c7. Thanks for your patience.

**Comment by astefanutti** [comment]
There is a follow-up commit e8afdfb76f654fe90d2947a8dedfa03a77b29473, that enables to view init container logs even if the pod itself is still in initialising phase. It'll be available in the next release.
