### ISSUE TITLE
[INFORMATION SHARE] A web based kubectl tool.

### ISSUE THREAD

**Issue by zhangliqiang** [astefanutti/kubebox#68]
Hi there,

We developed a web based kubectl tool, which helps you to manage kubernetes credentials and run kubectl command in web browser, so that you don't have to install kubectl on your local PC or some other servers, furthermore it can be used for a team.
Hopefully it's useful for you guys.

https://github.com/webkubectl/webkubectl

**Comment by astefanutti** [comment]
Thanks for the heads-up. We are thinking of adding a section about related tools. We'll add Webkubectl for sure.
