### ISSUE TITLE
Could not find the dockerfile to build astefanutti/kubebox:server

### ISSUE THREAD

**Issue by ylvmw** [astefanutti/kubebox#70]
We want to create the astefanutti/kubebox:server image ourselves, but we couldn't find the dockerfile to do it. Could you please let us know where it is or how to do that?

**Comment by astefanutti** [comment]
It's in the `docs` directory. It's been there because it was convenient, but we plan to move it into a proper `server` directory at some point.

**Comment by ylvmw** [comment]
Great! See it. Thank you so much for your quick reply!

**Comment by astefanutti** [comment]
Welcome. Let me close this as it's been answered.
