### ISSUE TITLE
We use dex

### ISSUE THREAD

**Issue by posix4e** [astefanutti/kubebox#73]
Anyway to use the jwt login to authenticate ?

**Comment by posix4e** [comment]
Also why does select file to import show up when I load https://github.com/astefanutti/kubebox/blob/master/docs/index.html?

**Comment by astefanutti** [comment]
It should be possible to use OIDC with Dex. With the Web version, the _Import_ button enables to import your _kubeconfig_ file that contains the connection details.

**Comment by astefanutti** [comment]
Let me close this. Feel free to re-open if you have further questions.
