### ISSUE TITLE
it is not supported copy text from log widget now ?  

### ISSUE THREAD

**Issue by 593769290** [astefanutti/kubebox#78]
in 0.4.0  0.5.0 version , I can press "shift" and mouse point to select txt in log  widget, and  then ctrl+insert  to select and shift+insert  to copy.

after updated to 0.7.0 version, this funtion has been gone. 
so , it is not supported copy text from log widget now ?  

the old related issues
https://github.com/astefanutti/kubebox/issues/17
https://github.com/astefanutti/kubebox/issues/10

**Comment by astefanutti** [comment]
It is not yet supported. We will work on #17 ASAP. I'm actually surprised it used to be working in previous versions.

**Comment by 593769290** [comment]
in 0.4.0 0.5.0 version ,it can copy log text, but include some unuseful text ,the border chararcter  "|".
I wish in the new implement, it could be excluded the border chararcter "|".

![image](https://user-images.githubusercontent.com/17897483/74307503-7b7b3680-4da0-11ea-93db-a2e005cd3cbd.png)

====================================================================
│2020-02-12 14:00:53.998  INFO 26 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms                                                       │
│2020-02-12 14:00:58.998  INFO 26 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms                                                       │
│2020-02-12 14:01:03.998  INFO 26 --- [a-EvictionTimer] c.n.e.registry.AbstractInstanceRegistry  : Running the evict task with compensationTime 0ms 
====================================================================

**Comment by astefanutti** [comment]
I wonder what could have broken it in 0.7.0, as it is provided by the terminal and not Kubebox.

Anyway, we intent to provide proper clipboard support for the log widget. It should work as the remote exec terminal, that already has copy/paste support.

May I suggest that you vote for #17 and close that issue?

**Comment by 593769290** [comment]
OK  thx y。
