### ISSUE TITLE
Clicking on 'e' to show events does nothing

### ISSUE THREAD

**Issue by cfontes** [astefanutti/kubebox#87]
That is it, everything else works perfectly.

Pressing 'e' doesn't bring up anything neither does ctrl+e

**Comment by astefanutti** [comment]
Events support has landed in `master` branch but has yet to be released. We are polishing it a bit, and plan to cut 0.8.0 release in the upcoming days.

**Comment by astefanutti** [comment]
@cfontes, 0.8.0 version has just been released: https://github.com/astefanutti/kubebox/releases/tag/v0.8.0.

Do not hesitate to provide feedback. Thanks for your patience!

**Comment by cfontes** [comment]
Works like a charm! Thanks for this I am using the kubernetes dashboard less and less with your software!
