### ISSUE TITLE
I can't scroll the logs using shortcuts on Lubuntu

### ISSUE THREAD

**Issue by cfontes** [astefanutti/kubebox#95]
First of all thanks for Kubebox, it's just great I have almost replaced Kubernetes dashboard with it by now, I love it.

The one thing that I cannot get to work is log scrolling page or line, I am using Lubuntu and have tried it in all terminals available nothing scrolls unless I click on the log section of kubebox, then it works perfectly but it kind of kills the purpose of shortcuts to have to click on the section.

Maybe Lubuntu is hijacking the shortcut somehow but then I think it would not work after I click on the log section, I've searched and I cannot find a mapping using G, Shift +G or any of the other ones.

So I was wondering if this is an know issue, I am not sure why it doesn't work unless it has focus on the log section.

Thank you.

**Comment by astefanutti** [comment]
Thanks a lot for the feedback!

The lack of focus management is a general issue, especially for terminals that do not support mouse events. We plan to rework the UI, so that it is possible to use every functionality using the keyboard only.

This relates to #31.

**Comment by cfontes** [comment]
No problem, I will watch it.

Thanks!

**Comment by astefanutti** [comment]
It's been fixed with #104.
