### ISSUE TITLE
Add tab key as key bind to toggle between 'pods' and 'log'

### ISSUE THREAD

**Issue by frudolph77** [astefanutti/kubebox#98]
It would be nice if <kbd>Tab</kbd>  toggles between the Pods-List and the Log so that i don't have to use a mouse for that.

**Comment by astefanutti** [comment]
Thanks for the suggestion. We plan to work on the support of _mouse-less_ navigation. This relates to #31 and #59.

**Comment by frudolph77** [comment]
I've found a solution, see pull request #104

**Comment by astefanutti** [comment]
Fixed with #104.
